services:
  backend:
    build:
      context: ./lang_portal_backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./lang_portal_backend:/app
      - ./lang_portal_backend/words.db:/app/words.db
    environment:
      - DEBUG=1
      - DOCKER_CONTAINER=1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    command: >
      bash -c "python manage.py migrate &&
               python manage.py load_seed_data &&
               python manage.py seed_data &&
               python scripts/seed_sentence_builder.py &&
               python manage.py runserver 0.0.0.0:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./lang_portal_frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./lang_portal_frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8080}
      - VITE_DOCUMENT_SUMMARY_URL=http://localhost:8501
    depends_on:
      backend:
        condition: service_started
      docsum-frontend:
        condition: service_started
    restart: unless-stopped

  docsum-api:
    build:
      context: ./opea-comps/docsum_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_DEFAULT_REGION}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET_NAME=genai-docsum-shehzad
      - BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID}
      - BEDROCK_REGION=${AWS_DEFAULT_REGION}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/google_credentials.json
    volumes:
      - ./opea-comps/docsum_service/data:/app/data
      - ./opea-comps/docsum_service/audio_cache:/app/audio_cache
      - ./opea-comps/docsum_service/credentials:/app/credentials
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  docsum-frontend:
    build:
      context: ./opea-comps/docsum_service
      dockerfile: Dockerfile
    command: streamlit run frontend/streamlit_app.py --server.port 8501
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://docsum-api:8002
      - INTERNAL_API_URL=http://docsum-api:8002
    depends_on:
      docsum-api:
        condition: service_healthy
    volumes:
      - ./opea-comps/docsum_service/frontend:/app/frontend
    restart: unless-stopped

volumes:
  frontend_node_modules:
