services:
  backend:
    build:
      context: ./lang_portal_backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./lang_portal_backend:/app
    environment:
      - DEBUG=1
      - DOCKER_CONTAINER=1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - POSTGRES_DB=lang_portal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./lang_portal_frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./lang_portal_frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8080}
      - VITE_DOCUMENT_SUMMARY_URL=${VITE_DOCUMENT_SUMMARY_URL:-http://localhost:8501}
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lang_portal
    ports:
      - "5432:5432"
    restart: unless-stopped

  docsum-api:
    build:
      context: ./opea-comps/docsum_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_DEFAULT_REGION}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID}
      - BEDROCK_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - ./opea-comps/docsum_service/data:/app/data
      - ./opea-comps/docsum_service/audio_cache:/app/audio_cache
      - ./opea-comps/docsum_service/credentials:/app/credentials
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  docsum-frontend:
    build:
      context: ./opea-comps/docsum_service
      dockerfile: Dockerfile
    command: streamlit run frontend/streamlit_app.py --server.port 8501
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://docsum-api:8002
      - INTERNAL_API_URL=http://docsum-api:8002
    depends_on:
      docsum-api:
        condition: service_healthy
    volumes:
      - ./opea-comps/docsum_service/frontend:/app/frontend
    restart: unless-stopped

volumes:
  postgres_data:
  frontend_node_modules:
