# Generated by Django 5.0.2 on 2025-03-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studysession',
            old_name='created_at',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='studysession',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
