# Generated by Django 5.0.2 on 2025-04-05 09:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_created_at_studysession_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordMatchingGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=10)),
                ('correct_answers', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WordMatchingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(unique=True)),
                ('games_played', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('best_score', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='difficulty_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='word',
            name='usage_frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WordMatchingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.TextField(null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('response_time', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.wordmatchinggame')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.word')),
            ],
            options={
                'unique_together': {('game', 'word')},
            },
        ),
    ]
