# Generated by Django 5.0.2 on 2025-04-05 12:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_wordmatchinggame_wordmatchingstats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
                ('total_cards', models.IntegerField(default=10)),
                ('cards_reviewed', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(unique=True)),
                ('cards_reviewed', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_level', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.flashcardgame')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.word')),
            ],
            options={
                'unique_together': {('game', 'word')},
            },
        ),
    ]
