# Generated by Django 5.0.2 on 2025-04-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_flashcardgame_flashcardstats_flashcardreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardgame',
            name='words',
            field=models.ManyToManyField(through='api.FlashcardReview', to='api.word'),
        ),
    ]
