# Generated by Django 5.0.2 on 2025-04-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_flashcardgame_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='etymology',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='example',
            field=models.TextField(null=True),
        ),
    ]
