# Generated by Django 5.0.2 on 2025-04-09 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_word_etymology_word_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentencePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('example', models.TextField(blank=True, null=True)),
                ('difficulty_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Word Categories',
            },
        ),
        migrations.CreateModel(
            name='UserSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('is_valid', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sentencepattern')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urdu_word', models.CharField(max_length=100)),
                ('roman_urdu', models.CharField(blank=True, max_length=100, null=True)),
                ('english_translation', models.CharField(max_length=100)),
                ('difficulty_level', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='api.wordcategory')),
            ],
        ),
    ]
