# Generated by Django 5.0.2 on 2025-04-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sentencepattern_wordcategory_usersentence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
