# version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env   
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload
    ports:
      - "8002:8002"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID}
      - BEDROCK_REGION=${BEDROCK_REGION}
    volumes:
      - ./data:/app/data
      - ./audio_cache:/app/audio_cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - docsum_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: streamlit run frontend/streamlit_app.py --server.port 8501
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8002
      - INTERNAL_API_URL=http://api:8002
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./frontend:/app/frontend
      - ./frontend/.streamlit:/app/frontend/.streamlit
    networks:
      - docsum_network

networks:
  docsum_network:
    driver: bridge

volumes:
  audio_cache:
